sample_app.1/config/routes.rb
Rails.application.routes.draw do

  get 'teacher/index'

  get 'teacher/new'

  get 'teacher/show'

  resources :responses

  resources :questionnaires
  resources :answers

  resources :students

  devise_for :users
  root 'static_pages#home' # asi se setea la pagina de inicio
  resources :quizzes
  resources :questions
  #get '/quizzes/show'#  get '/quizzes'
  get  '/students/todos'
  get  '/help', to: 'static_pages#help'
  get  '/about' ,    to:  'static_pages#about'
  get   '/contact' ,  to:  'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/estudiante/login',  to: 'users#estudiante' , as: 'estudiante'
  get  '/profesor/registrar',  to: 'users#registrar' , as: 'registrar'
  get  '/estudiante/cuestionario',  to: 'users#cuestionario' , as: 'cuestionario'
  get  '/profesor/pregunta',  to: 'users#pregunta' , as: 'pregunta'
  get  '/estudiante/terminado',  to: 'users#terminado' , as: 'terminado'
  get  '/respuestapregutna/:quiz/:user_id/',  to: 'questionnaires#index' , as: 'respuestapregutnaindex'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_app.1/app/models/answer.rb
class Answer < ApplicationRecord
end

sample_app.1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app.1/app/models/question.rb
class Question < ApplicationRecord
  #belongs_to :quiz
  validates :description, presence: true,length: {minimum: 5}
  validates :answer_one, presence: true
  validates :answer_two, presence: true
  validates :answer_three, presence: true
  validates :answer_four, presence: true
  validates_format_of :description, :with => /\A^([^0-9]*)$+\z/, :message => "Invalid! Alphanumerics only."
end

sample_app.1/app/models/quiz.rb
class Quiz < ApplicationRecord
  #validations rails
  validates :description, presence: true, uniqueness: true, length: {minimum: 10}
  #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  #http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_format_of
  belongs_to :user
  #has_many :questions
end

sample_app.1/app/models/response.rb
class Response < ApplicationRecord
end

sample_app.1/app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
end

sample_app.1/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :quizzes
end

sample_app.1/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end

  def new
  end

  def show
  end

  def create
    @answer = Answer.new(description: params[:answer][:description],
                        question_id: params[:answer][:question_id]
                        correct: params[:answer][:correct])
    if @answer.save
    end
  end

end

sample_app.1/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
# Metodos para ver
  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
    #ApplicationController.set_quiz(5)
    @var = set_quiz(@quiz.id)
  end
#

#Creacion de articulos
  def new  # solo crea el articulo pero no es persistente
    @quiz = Quiz.new
  end

  def create
    begin
      prng1 = rand(100000..999999)
      @quiz =current_user.quizzes.new(description: params[:quiz][:description], pin: prng1,
                                      active: true)
      if @quiz.save
        redirect_to '/quizzes/'+ @quiz.id.to_s
      else
        render :new
      end
    rescue
      @quiz = Quiz.find_by(pin: params[:quiz][:pin])
       logger.debug "Inicado en quiz"
       begin
           logger.debug @quiz.description
           if @quiz.active
             redirect_to '/students/new'
             set_quiz_student(@quiz.id)
           else
             respond_to do |format|
               format.html { redirect_to '/students', notice: 'No existe con ese codigo' }

             end
             #redirect_to '/'
           end
           set_error(0)
           @error = get_error
       rescue
            logger.debug "no existe el quiz"
            set_error(1)
            @error = get_error
            respond_to do |format|
              format.html { redirect_to '/students', notice: 'No existe con ese codigo' }
              format.json { render json: @quiz.errors, status: :unprocessable_entity }
            end
       end
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @var = set_quiz(@quiz.id)
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update(description: params[:quiz][:description])
  end

  def destroy
    @quiz.destroy
  end

end

sample_app.1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def estudiante
  end
  def registrar
  end
  def cuestionario
  end
  def pregunta
  end
end

sample_app.1/app/helpers/answers_helper.rb
module AnswersHelper
end

sample_app.1/app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
    
end

sample_app.1/app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

sample_app.1/app/helpers/questions_helper.rb
module QuestionsHelper
end

sample_app.1/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

sample_app.1/app/helpers/responses_helper.rb
module ResponsesHelper
end

sample_app.1/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app.1/app/helpers/students_helper.rb
module StudentsHelper
end

sample_app.1/app/helpers/teacher_helper.rb
module TeacherHelper
end

sample_app.1/app/helpers/users_helper.rb
module UsersHelper
end

sample_app.1/app/views/layouts/_error.html.erb
<h1>error<h1>

sample_app.1/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Echo por Joel Rodriguez y Angel Guerra
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

sample_app.1/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Proyecto", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Help",    help_path %></li>
        <%if user_signed_in?%>
          <li><%= link_to "Salir", destroy_user_session_path, method: :get  %></li>
        <%else%>
          <li><%= link_to "Registro", new_user_registration_path  %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

sample_app.1/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

sample_app.1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'stylesheet/custom', 'data-turbolinks-track': 'reload'  %>
    <%= stylesheet_link_tag 'stylesheet/static_pages', 'data-turbolinks-track': 'reload' %>

    <%= yield :estilo %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>